# Site settings
title: Ad Librum
email: info@adlibrum.hu
description: > # this means to ignore newlines until "baseurl:"
  Az <strong>Ad Librum Kft.</strong> kortárs szép- és szórakoztató irodalmat ad ki <em>Ad Librum Kiadó</em> néven, továbbá ismeretterjesztő és szakirodalmat <em>Expert Books</em> név alatt és tudományos köteteket <em>StormingBrain Kiadó</em> márkanévvel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hungaricus.github.io/oldjekyll" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

theme: jekyll-theme-architect
